In [1]:
l = [ 1,2,3,4,5,6,7]
#     0,1,2,3,4,5,6
#   -7,-6,-5,-4,-3,-2,-1

In [2]:
l[-4:1:-2] # ? [start:end:step]

[4]

In [3]:
l[  : : -2 ]

[7, 5, 3, 1]

In [4]:
import numpy as np 

In [5]:
a = np.array([var for var in range(100)])

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
a.shape

(100,)

In [8]:
a.ndim

1

In [9]:
a.dtype

dtype('int32')

In [10]:
l = np.array([
    [5,6,2,4],
    [6,4,3,2],
    [2,3,4,9],
    [4,6,3,2]
])

In [11]:
print(l)

[[5 6 2 4]
 [6 4 3 2]
 [2 3 4 9]
 [4 6 3 2]]


In [12]:
l[1:3,1:3]

array([[4, 3],
       [3, 4]])

In [18]:
l[-2:,[0,2,3]]

array([[2, 4, 9],
       [4, 3, 2]])